# Generated by Django 5.2 on 2025-05-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_settingsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchModel',
        ),
        migrations.DeleteModel(
            name='SettingsModel',
        ),
    ]
