# Generated by Django 5.2 on 2025-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_branchmodel_delete_settingsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('homeNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('flatNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('intercomCode', models.CharField(blank=True, max_length=50, null=True)),
                ('additionalPhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
