# Generated by Django 5.2 on 2025-05-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_branchmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchModel',
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='main.usermodel'),
        ),
    ]
